name: " Feature Request "
description: "Suggest a new idea or improvement."
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
  - type: input
    attributes:
      label: Why is this feature important?
